FROM node:lts-alpine

RUN mkdir -p /usr/src/order-manager/client

WORKDIR /usr/src/order-manager/client

# ENV PATH /usr/src/order-manager/client/node_modules/.bin:$PATH

EXPOSE 3000
# RUN npm run dev