version: '3.8'

services:
    backend:
        restart: always
        build: 
            context: ./backend
            dockerfile: Dockerfile.dev
        # command: python manage.py run -h 0.0.0.0
        volumes:
            - ./backend:/backend
        ports: 
            - 5000:5000
        env_file: ./backend/.env.dev
        depends_on:
            - db
        networks:
            - expense-control-net
        

    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
            - ./frontend:/frontend
            - ./frontend:/frontend/node_modules
        ports: 
            - 8080:8080
        command: sh -c "npm install && npm run serve"
        environment: 
            - CHOKIDAR_USEPOLLING=true
        networks:
            - expense-control-net

    db:
        restart: always
        image: postgres:11
        container_name: expense-control-db
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ./postgres-data/postgres:/var/lib/postgresql/data
        networks:
            - expense-control-net
    
networks:
    expense-control-net:
        driver: bridge
    