FROM python:3.8-alpine

WORKDIR /usr/src/order-manager/server

COPY . .

RUN pip install -r requirements-dev.txt

# RUN flask db init

# RUN flask db migrate -m "initial migration"

# RUN flask db upgrade

