FROM python:3.9-slim-buster

WORKDIR /backend


RUN pip install poetry

RUN poetry config virtualenvs.in-project true
    # && poetry config virtualenvs.create true \
    # && poetry install

RUN apt-get update && apt-get install -y netcat


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY . .

# ENTRYPOINT ["/backend/entrypoint.sh"]